#!/bin/bash
set -e
cd "$(dirname "$0")/.."

cd test

versions=${1-python2 python3 pypy pypy3}

for version in $versions; do
  version_dir="venv-$version"
  if [ ! -e "$version_dir/bin/activate" ]; then
    virtualenv --python="$(which "$version")" "$version_dir"
    source "$version_dir/bin/activate"
    pip install pytest
  else
    source "$version_dir/bin/activate"
  fi
  echo "Testing against $(python --version 2>&1)"
  pip install --upgrade ../

  py.test ./*_tests.py
done
